// yes, it's a valid program
// the call to std::cout is inside 5 levels deep
// in the scope of the main() function
int main(void) {}
